name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
  
  linux:
    name: Linux
    runs-on: ubuntu-24.04
    container: swift:6.0.3
    steps:
      - uses: actions/checkout@v4
      - name: Swift Version
        run: swift --version
      - name: Build (Debug)
        run: swift build -c debug
      - name: Build (Release)
        run: swift build -c release
      - name: Test (Debug)
        run: swift test -c debug
